# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ jacocoBadgeGen ]
  pull_request:
    branches: [ jacocoBadgeGen ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pandas/pom.xml


    - name: jacoco-badge-generator
      id: integration1
      # You may pin to the exact commit or the version.
      # uses: cicirello/jacoco-badge-generator@bce93b1f42572a20200386583e26fe0c397c0944
      uses: cicirello/jacoco-badge-generator@v2.6.1
      with:
        # Full path, relative to the root of the repository, to the jacoco csv file(s), including filename(s)
        jacoco-csv-file: pandas/target/site/jacoco-ut/jacoco.csv # optional, default is target/site/jacoco/jacoco.csv
        # The directory for storing badges, relative to the root of the repository.
        badges-directory: .github/badges # optional, default is .github/badges
        # The filename of the coverage badge.
        coverage-badge-filename: jacoco.svg # optional, default is jacoco.svg
        # The filename of the branches coverage badge.
        branches-badge-filename: branches.svg # optional, default is branches.svg
        # Controls whether or not to generate the coverage badge.
        generate-coverage-badge: true # optional, default is true
        # Controls whether or not to generate the branches coverage badge.
        generate-branches-badge: true # optional
        # Controls what happens if one or more jacoco.csv files do not exist.
        on-missing-report: fail # optional, default is fail
        # Enables failing workflow run when coverage below specified threshold.
        fail-if-coverage-less-than: 0 # optional, default is 0
        # Enables failing workflow run when branches coverage below specified threshold.
        fail-if-branches-less-than: 0 # optional, default is 0

    - name: Log integration test outputs with a single jacoco.csv
      run: |
        echo "coverage = ${{ steps.integration1.outputs.coverage }}"
        echo "branch coverage = ${{ steps.integration1.outputs.branches }}"
