# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ jacocoBadgeGen ]
  pull_request:
    branches: [ jacocoBadgeGen ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: echo "Debugging"

    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pandas/pom.xml

    - name: jacoco-badge-generator
      # You may pin to the exact commit or the version.
      # uses: cicirello/jacoco-badge-generator@bce93b1f42572a20200386583e26fe0c397c0944
      uses: cicirello/jacoco-badge-generator@v2.6.1
      with:
        # Full path, relative to the root of the repository, to the jacoco csv file(s), including filename(s)
        jacoco-csv-file: target/site/jacoco-ut/jacoco.csv # optional, default is target/site/jacoco/jacoco.csv
        # The directory for storing badges, relative to the root of the repository.
        badges-directory: .github/badges # optional, default is .github/badges
        # The filename of the coverage badge.
        coverage-badge-filename: jacoco.svg # optional, default is jacoco.svg
        # The filename of the branches coverage badge.
        branches-badge-filename: branches.svg # optional, default is branches.svg
        # Controls whether or not to generate the coverage badge.
        generate-coverage-badge: true # optional, default is true
        # Controls whether or not to generate the branches coverage badge.
        generate-branches-badge: # optional
        # Text for the left-side of the coverage badge.
        coverage-label: coverage # optional, default is coverage
        # Text for the left-side of the branches coverage badge.
        branches-label: branches # optional, default is branches
        # Controls what happens if one or more jacoco.csv files do not exist.
        on-missing-report: fail # optional, default is fail
        # Enables failing workflow run when coverage below specified threshold.
        fail-if-coverage-less-than: 0 # optional, default is 0
        # Enables failing workflow run when branches coverage below specified threshold.
        fail-if-branches-less-than: 0 # optional, default is 0
        # Enables failing workflow if coverage is less than it was on previous run.
        fail-on-coverage-decrease: # optional
        # Enables failing workflow if branches coverage is less than it was on previous run.
        fail-on-branches-decrease: # optional
        # List of coverage percentages as cutoffs for each color.
        intervals: 100 90 80 70 60 0 # optional, default is 100 90 80 70 60 0
        # List of colors to use ordered by coverage interval, best coverage to worst.
        colors: #4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44 # optional, default is #4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44
        # Controls whether or not to generate the coverage JSON endpoint.
        generate-coverage-endpoint: # optional
        # Controls whether or not to generate the branches coverage JSON endpoint.
        generate-branches-endpoint: # optional
        # The filename of the coverage JSON endpoint.
        coverage-endpoint-filename: jacoco.json # optional, default is jacoco.json
        # The filename of the branches coverage JSON endpoint.
        branches-endpoint-filename: branches.json # optional, default is branches.json
        # Controls whether or not to generate a JSON file containing the coverage percentages as floating-point values.
        generate-summary: # optional
        # The filename of the summary file.
        summary-filename: coverage-summary.json # optional, default is coverage-summary.json
